# Generated by Django 3.0.5 on 2020-05-09 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contnets',
            new_name='contents',
        ),
    ]
